name = "babyshark"
description = "Flows-first PCAP TUI (case files, gorgeous UX). Do do do do."
homepage = "https://github.com/vignesh07/babyshark"
alternatives = [ ]
version = "0.3.0"
updated = "2026-02-27"
package-url = "https://github.com/vignesh07/babyshark/releases/download/v{{version}}/babyshark-v{{version}}-linux-x64.tar.gz"

[extract]
strip = 0

[[extract.files]]
source = "babyshark"
target = "{{vars.bin-path}}/babyshark"
mode = "0755"
