name = "carapace"
description = "multi-shell multi-command argument completer"
homepage = "https://carapace.sh"
alternatives = []
version = "1.6.2"
updated = "2026-02-10"
package-url = "https://github.com/carapace-sh/carapace-bin/releases/download/v{{version}}/carapace-bin_linux_amd64.tar.gz"

[extract]
strip = 0

[[extract.files]]
source = "carapace"
target = "{{vars.bin-path}}/carapace"
mode = "0755"
