name = "curlie"
description = "The power of curl, the ease of use of httpie."
homepage = "https://github.com/rs/curlie"
alternatives = [ "httpie", "xh",]
version = "1.7.2"
updated = ""
package-url = "https://github.com/rs/curlie/releases/download/v{{version}}/curlie_{{version}}_linux_amd64.tar.gz"

[extract]
strip = 0
[[extract.files]]
source = "curlie"
target = "{{vars.bin-path}}/curlie"
mode = "0755"

