name = "dblab"
description = "The database client every command line junkie deserves."
homepage = "https://github.com/danvergara/dblab"
alternatives = [ "lazysql", "usql", ]
version = "0.34.2"
updated = "2026-01-24"
package-url = "https://github.com/danvergara/dblab/releases/download/v{{version}}/dblab_{{version}}_linux_amd64.tar.gz"

[extract]
strip = 0

[[extract.files]]
source = "dblab"
target = "{{vars.bin-path}}/dblab"
mode = "0755"
