name = "delta"
description = "A syntax-highlighting pager for git, diff, grep, and blame output"
homepage = "https://github.com/dandavison/delta"
alternatives = []
version = "0.18.1"
updated = "2024-05-09"
package-url = "https://github.com/dandavison/delta/releases/download/{{version}}/delta-{{version}}-x86_64-unknown-linux-musl.tar.gz"

[extract]
strip = 1
[[extract.files]]
source = "delta"
target = "{{vars.bin-path}}/delta"
mode = "0755"
