name = "devbox"
description = "Instant, easy, and predictable development environments"
homepage = "https://github.com/jetify-com/devbox"
alternatives = []
version = "0.12.0"
updated = "2024-06-28"
package-url = "https://github.com/jetify-com/devbox/releases/download/{{version}}/devbox_{{version}}_linux_amd64.tar.gz"

[extract]
strip = 0
[[extract.files]]
source = "devbox"
target = "{{vars.bin-path}}/devbox"
mode = "0755"
