name = "difftastic"
description = "a structural diff that understands syntax"
homepage = "https://github.com/Wilfred/difftastic"
alternatives = [ "diff",]
version = "0.60.0"
updated = "2024-08-01"
package-url = "https://github.com/Wilfred/difftastic/releases/download/{{version}}/difft-x86_64-unknown-linux-gnu.tar.gz"

[extract]
strip = 0
prefix = "{{vars.bin-path}}"
