name = "direnv"
description = "unclutter your .profile"
homepage = "https://github.com/direnv/direnv"
alternatives = []
version = "2.35.0"
updated = "2024-10-07"
package-url = "https://github.com/direnv/direnv/releases/download/v{{version}}/direnv.linux-amd64"

[extract]
[[extract.files]]
source = "direnv.linux-amd64"
target = "{{vars.bin-path}}/direnv"
mode = "0755"
