name = "dotenvx"
description = "a better dotenvâ€“from the creator of `dotenv`"
homepage = "https://dotenvx.com"
alternatives = [ "cat",]
version = "1.51.0"
updated = "2025-09-24"
package-url = "https://github.com/dotenvx/dotenvx/releases/download/v{{version}}/dotenvx-{{version}}-linux-x86_64.tar.gz"

[extract]
strip = 0

[[extract.files]]
source = "dotenvx"
target = "{{vars.bin-path}}/dotenvx"
mode = "0755"
