name = "dust"
description = "A more intuitive version of du in rust"
homepage = "https://github.com/bootandy/dust"
alternatives = [ "du",]
version = "1.2.2"
updated = "2025-07-06"
package-url = "https://github.com/bootandy/dust/releases/download/v{{version}}/dust-v{{version}}-x86_64-unknown-linux-musl.tar.gz"

[extract]
strip = 1

[[extract.files]]
source = "dust"
target = "{{vars.bin-path}}/dust"
mode = "0755"
