name = "eza"
description = "A modern alternative to ls"
homepage = "https://github.com/eza-community/eza"
alternatives = [ "ls", "lsd",]
version = "0.19.2"
updated = "2024-09-05"
package-url = "https://github.com/eza-community/eza/releases/download/v{{version}}/eza_x86_64-unknown-linux-musl.tar.gz"
post-commands = [ "ln -s {{vars.bin-path}}/eza {{vars.bin-path}}/exa",]

[extract]
strip = 0
prefix = "{{vars.bin-path}}"
