name = "fq"
description = "jq for binary formats - tool, language and decoders for working with binary and text formats"
homepage = "https://github.com/wader/fq"
alternatives = []
version = "0.12.0"
updated = ""
package-url = "https://github.com/wader/fq/releases/download/v{{version}}/fq_{{version}}_linux_amd64.tar.gz"

[extract]
strip = 0
[[extract.files]]
source = "fq"
target = "{{vars.bin-path}}/fq"
mode = "0755"

