name = "git-who"
description = "Git blame for file trees"
homepage = "https://github.com/sinclairtarget/git-who"
alternatives = []
version = "1.0"
updated = "2025-05-18"
package-url = "https://github.com/sinclairtarget/git-who/releases/download/v{{version}}/gitwho_v{{version}}_linux_amd64.tar.gz"
version-pattern = "v\\d+\\.\\d+$"

[extract]
strip = 0

[[extract.files]]
source = "linux_amd64/git-who"
target = "{{vars.bin-path}}/git-who"
mode = "0755"
