name = "hexyl"
description = "A command-line hex viewer"
homepage = "https://github.com/sharkdp/hexyl"
alternatives = []
version = "0.16.0"
updated = "2024-12-27"
package-url = "https://github.com/sharkdp/hexyl/releases/download/v{{version}}/hexyl-v{{version}}-i686-unknown-linux-musl.tar.gz"

[extract]
strip = 1

[[extract.files]]
source = "hexyl"
target = "{{vars.bin-path}}/hexyl"
mode = "0755"
