name = "jd"
description = "JSON diff and patch"
homepage = "https://github.com/josephburnett/jd"
alternatives = []
version = "2.5.0"
updated = "2026-02-23"
package-url = "https://github.com/josephburnett/jd/releases/download/v{{version}}/jd-amd64-linux"

[extract]
strip = 0

[[extract.files]]
source = "jd-amd64-linux"
target = "{{vars.bin-path}}/jd"
mode = "0755"
