name = "k9s"
description = "Kubernetes CLI To Manage Your Clusters In Style!"
homepage = "https://github.com/derailed/k9s"
alternatives = []
version = "0.50.4"
updated = "2025-04-19"
package-url = "https://github.com/derailed/k9s/releases/download/v{{version}}/k9s_Linux_amd64.tar.gz"

[extract]
strip = 0

[[extract.files]]
source = "k9s"
target = "{{vars.bin-path}}/k9s"
mode = "0755"
