name = "lazyjournal"
description = "A TUI for reading logs from journald, auditd, file system, Docker containers, ..."
homepage = "https://github.com/Lifailon/lazyjournal"
alternatives = []
version = "0.7.9"
updated = "2025-05-29"
package-url = "https://github.com/Lifailon/lazyjournal/releases/download/{{version}}/lazyjournal-{{version}}-linux-amd64"

[extract]
strip = 0

[[extract.files]]
source = "lazyjournal-{{version}}-linux-amd64"
target = "{{vars.bin-path}}/lazyjournal"
mode = "0755"
