name = "llmfit"
description = "206 models. 30 providers. One command to find what runs on your hardware."
homepage = "https://github.com/AlexsJones/llmfit"
alternatives = [ ]
version = "0.4.9"
updated = "2026-02-27"
package-url = "https://github.com/AlexsJones/llmfit/releases/download/v{{version}}/llmfit-v{{version}}-x86_64-unknown-linux-musl.tar.gz"

[extract]
strip = 1

[[extract.files]]
source = "llmfit"
target = "{{vars.bin-path}}/llmfit"
mode = "0755"
