name = "mergiraf"
description = "A syntax-aware git merge driver for a growing collection of programming languages and file formats."
homepage = "https://mergiraf.org"
alternatives = []
version = "0.16.1"
updated = "2025-11-07"
package-url = "https://codeberg.org/mergiraf/mergiraf/releases/download/v{{version}}/mergiraf_x86_64-unknown-linux-gnu.tar.gz"
query-url = "https://github.com/qundao/mirror-mergiraf/archive/refs/tags/v{{version}}.tar.gz"

[extract]
strip = 0

[[extract.files]]
source = "mergigraf"
target = "{{vars.bin-path}}/mergigraf"
mode = "0755"
