name = "miniserve"
description = "For when you really just want to serve some files over HTTP right now!"
homepage = "https://github.com/svenstaro/miniserve"
alternatives = [ "simple-http-server", "see", "binserve", "http" ]
version = "0.28.0"
updated = "2024-09-12"
package-url = "https://github.com/svenstaro/miniserve/releases/download/v{{version}}/miniserve-{{version}}-x86_64-unknown-linux-musl"

[extract]
strip = 0

[[extract.files]]
source = "miniserve-{{version}}-x86_64-unknown-linux-musl"
target = "{{vars.bin-path}}/miniserve"
mode = "0755"
