name = "multi-git-status"
description = "Show uncommitted, untracked and unpushed changes for multiple Git repos"
homepage = "https://github.com/fboender/multi-git-status/archive/refs/tags/{{version}}.tar.gz"
alternatives = []
version = "2.3"
updated = "2024-10-31"
package-url = "https://github.com/fboender/multi-git-status/archive/refs/tags/{{version}}.tar.gz"
version-pattern = "^\\d+\\.\\d+(\\.\\d+)?$"

[extract]
strip = 1
[[extract.files]]
source = "mgitstatus"
target = "{{vars.bin-path}}/mgitstatus"
mode = "0755"
