name = "navi"
description = "An interactive cheatsheet tool for the command-line"
homepage = "https://github.com/denisidoro/navi"
alternatives = []
version = "2.23.0"
updated = "2023-12-10"
package-url = "https://github.com/denisidoro/navi/releases/download/v{{version}}/navi-v{{version}}-x86_64-unknown-linux-musl.tar.gz"

[extract]
strip = 1
[[extract.files]]
source = "navi"
target = "{{vars.bin-path}}/navi"
mode = "0755"
