name = "onefetch"
description = "Command-line Git information tool"
homepage = "https://onefetch.dev"
alternatives = []
version = "2.24.0"
updated = "2025-04-13"
package-url = "https://github.com/o2sh/onefetch/releases/download/{{version}}/onefetch-linux.tar.gz"

[extract]
strip = 0

[[extract.files]]
source = "onefetch"
target = "{{vars.bin-path}}/onefetch"
mode = "0755"
