name = "openapi-generator"
description = "OpenAPI Generator allows generation of API client libraries (SDK generation), server stubs, documentation and configuration automatically given an OpenAPI Spec (v2, v3)"
homepage = "https://openapi-generator.tech"
alternatives = []
version = "7.16.0"
updated = "2025-09-28"
query-url = "https://github.com/OpenAPITools/openapi-generator/archive/refs/tags/v{{version}}.tar.gz"
package-url = "https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/{{version}}/openapi-generator-cli-{{version}}.jar"
version-pattern = "v\\d+\\.\\d+\\.\\d+$"

#
# build configuration
#

[build]
query-url = "https://github.com/OpenAPITools/openapi-generator/archive/refs/tags/v{{version}}.tar.gz"
package-url = "https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/{{version}}/openapi-generator-cli-{{version}}.jar"
version-pattern = "v\\d+\\.\\d+\\.\\d+$"

[[build.publish]]
repository-name = "packages"
repository-path = "openapi-generator"
files = ["openapi-generator-cli-{{version}}.jar"]
