name = "oryx"
description = "TUI for sniffing network traffic using eBPF on Linux"
homepage = "https://github.com/pythops/oryx"
alternatives = [ ]
version = "0.8.0"
updated = "2026-02-04"
package-url = "https://github.com/pythops/oryx/releases/download/v{{version}}/oryx-x86_64-unknown-linux-musl"

[extract]
strip = 0

[[extract.files]]
source = "oryx-x86_64-unknown-linux-musl"
target = "{{vars.bin-path}}/oryx"
mode = "0755"
