name = "podman-tui"
description = "Podman Terminal UI"
homepage = "https://github.com/containers/podman-tui"
alternatives = [ ]
version = "1.10.0"
updated = "2026-01-24"
package-url = "https://github.com/containers/podman-tui/releases/download/v{{version}}/podman-tui-release-linux_amd64.zip"

[extract]
strip = 2

[[extract.files]]
source = "podman-tui"
target = "{{vars.bin-path}}/podman-tui"
mode = "0755"
