name = "powerline-go"
description = "A beautiful and useful low-latency prompt for your shell, written in go"
homepage = "https://github.com/justjanne/powerline-go"
alternatives = [ "starship",]
version = "1.26"
updated = "2026-01-14"
package-url = "https://github.com/justjanne/powerline-go/releases/download/v{{version}}/powerline-go-linux-amd64"
version-pattern = "^v\\d+\\.\\d+(\\.\\d+)?$"

[extract]
strip = 0

[[extract.files]]
source = "powerline-go-linux-amd64"
target = "{{vars.bin-path}}/powerline-go"
mode = "0755"
