name = "procs"
description = "A modern replacement for ps written in Rust"
homepage = "https://github.com/dalance/procs"
alternatives = [ "ps",]
version = "0.14.7"
updated = "2024-10-22"
package-url = "https://github.com/dalance/procs/releases/download/v{{version}}/procs-v{{version}}-x86_64-linux.zip"

[extract]
strip = 0
prefix = "{{vars.bin-path}}"
