name = "rainfrog"
description = "a database management tui for postgres"
homepage = "https://crates.io/crates/rainfrog"
alternatives = []
version = "0.3.14"
updated = "2026-02-04"
package-url = "https://github.com/achristmascarl/rainfrog/releases/download/v{{version}}/rainfrog-v{{version}}-i686-unknown-linux-musl.tar.gz"

[extract]
strip = 0

[[extract.files]]
source = "rainfrog"
target = "{{vars.bin-path}}/rainfrog"
mode = "0755"
