name = "regctl"
description = "Docker and OCI Registry Client in Go and tooling using those libraries."
homepage = "https://regclient.org"
alternatives = []
version = "0.11.2"
updated = "2026-02-23"
package-url = "https://github.com/regclient/regclient/releases/download/v{{version}}/regctl-linux-amd64"

[extract]
strip = 0

[[extract.files]]
source = "regctl-linux-amd64"
target = "{{vars.bin-path}}/regctl"
mode = "0755"
