name = "runme"
description = "DevOps Workflows Built with Markdown"
homepage = "https://github.com/stateful/runme"
alternatives = []
version = "3.12.7"
updated = "2025-03-20"
package-url = "https://github.com/stateful/runme/releases/download/v{{version}}/runme_linux_x86_64.tar.gz"

[extract]
strip = 0

[[extract.files]]
source = "runme"
target = "{{vars.bin-path}}/runme"
mode = "0755"
