name = "scc"
description = "Sloc, Cloc and Code: scc is a very fast accurate code counter with complexity calculations and COCOMO estimates written in pure Go"
homepage = "https://github.com/boyter/scc"
alternatives = [ "sloc", "tokei",]
version = "3.5.0"
updated = "2025-02-17"
package-url = "https://github.com/boyter/scc/releases/download/v{{version}}/scc_Linux_x86_64.tar.gz"

[extract]
strip = 0

[[extract.files]]
source = "scc"
target = "{{vars.bin-path}}/scc"
mode = "0755"
