name = "sidecar"
description = "Use sidecar next to CLI agents for diffs, file trees, conversation history, and task management with td"
homepage = "https://github.com/marcus/sidecar"
alternatives = [ ]
version = "0.76.0"
updated = "2026-02-28"
package-url = "https://github.com/marcus/sidecar/releases/download/v{{version}}/sidecar_{{version}}_linux_amd64.tar.gz"

[extract]
strip = 0

[[extract.files]]
source = "sidecar"
target = "{{vars.bin-path}}/sidecar"
mode = "0755"
