name = "tailspin"
description = "A log file highlighter"
homepage = "https://github.com/bensadeh/tailspin"
alternatives = []
version = "5.4.3"
updated = "2025-05-25"
package-url = "https://github.com/bensadeh/tailspin/releases/download/{{version}}/tailspin-x86_64-unknown-linux-musl.tar.gz"

[extract]
strip = 0

[[extract.files]]
source = "tspin"
target = "{{vars.bin-path}}/tspin"
mode = "0755"
