name = "tokei"
description = "Count your code, quickly."
homepage = "https://github.com/XAMPPRocky/tokei"
alternatives = [ "sloc", "scc",]
version = "12.1.2"
updated = "2021-01-12"
package-url = "https://github.com/XAMPPRocky/tokei/releases/download/v{{version}}/tokei-x86_64-unknown-linux-musl.tar.gz"

[extract]
strip = 0
[[extract.files]]
source = "tokei"
target = "{{vars.bin-path}}/tokei"
mode = "0755"
