name = "topgrade"
description = "Upgrade all the things"
homepage = "https://github.com/topgrade-rs/topgrade"
alternatives = [ ]
version = "16.9.0"
updated = "2026-02-15"
package-url = "https://github.com/topgrade-rs/topgrade/releases/download/v{{version}}/topgrade-v{{version}}-x86_64-unknown-linux-musl.tar.gz"

[extract]
strip = 0

[[extract.files]]
source = "topgrade"
target = "{{vars.bin-path}}/topgrade"
mode = "0755"
