name = "upt"
description = "Universal Package-management Tool for any OS."
homepage = "https://github.com/sigoden/upt"
alternatives = []
version = "0.8.0"
updated = "2024-05-27"
package-url = "https://github.com/sigoden/upt/releases/download/v{{version}}/upt-v{{version}}-i686-unknown-linux-musl.tar.gz"

[extract]
strip = 0
[[extract.files]]
source = "upt"
target = "{{vars.bin-path}}/upt"
mode = "0755"
