name = "usql"
description = "Universal command-line interface for SQL databases"
homepage = "https://github.com/xo/usql"
alternatives = []
version = "0.19.16"
updated = "2025-01-13"
package-url = "https://github.com/xo/usql/releases/download/v{{version}}/usql_static-{{version}}-linux-amd64.tar.bz2"

[extract]
strip = 0

[[extract.files]]
source = "usql_static"
target = "{{vars.bin-path}}/usql"
mode = "0755"
