name = "uv"
description = "An extremely fast Python package and project manager, written in Rust."
homepage = "https://github.com/astral-sh/uv"
alternatives = ["pip", "pdm", "poetry", "rye"]
version = "0.4.16"
updated = "2024-09-25"
package-url = "https://github.com/astral-sh/uv/releases/download/{{version}}/uv-x86_64-unknown-linux-musl.tar.gz"

[extract]
strip = 1
prefix = "{{vars.bin-path}}"
