name = "websocat"
description = "Command-line client for WebSockets, like netcat (or curl) for ws:// with advanced socat-like functions"
homepage = "https://github.com/vi/websocat"
alternatives = []
version = "1.14.1"
updated = "2025-12-27"
package-url = "https://github.com/vi/websocat/releases/download/v{{version}}/websocat.x86_64-unknown-linux-musl"

[extract]
strip = 0

[[extract.files]]
source = "websocat.x86_64-unknown-linux-musl"
target = "{{vars.bin-path}}/websocat"
mode = "0755"
