name = "witr"
description = "Why is this running?"
homepage = "https://github.com/pranshuparmar/witr"
alternatives = []
version = "0.2.6"
updated = "2026-01-21"
package-url = "https://github.com/pranshuparmar/witr/releases/download/v{{version}}/witr-linux-amd64"

[extract]
strip = 0

[[extract.files]]
source = "witr-linux-amd64"
target = "{{vars.bin-path}}/witr"
mode = "0755"
