name = "yq"
description = "yq is a portable command-line YAML, JSON, XML, CSV, TOML and properties processor"
homepage = "https://github.com/mikefarah/yq"
alternatives = []
version = "4.44.5"
updated = "2024-11-16"
package-url = "https://github.com/mikefarah/yq/releases/download/v{{version}}/yq_linux_amd64.tar.gz"

[extract]
strip = 1
[[extract.files]]
source = "yq_linux_amd64"
target = "{{vars.bin-path}}/yq"
mode = "0755"
