name = "zsh-you-should-use"
description = "ZSH plugin that reminds you to use existing aliases for commands you just typed"
homepage = "https://github.com/MichaelAquilina/zsh-you-should-use/archive/refs/tags/{{version}}.tar.gz"
alternatives = []
version = "1.11.0"
updated = "2026-02-11"
package-url = "https://github.com/MichaelAquilina/zsh-you-should-use/archive/refs/tags/{{version}}.tar.gz"

[extract]
strip = 1
prefix = "{{vars.zsh-plugin-path}}/zsh-you-should-use"
